# An address to bind the HTTP server to.
bind-addr = "127.0.0.1:20654"

# The path to a Feedgen database file.
# db-path = "/var/lib/feedgen/feedgen.sqlite3"
db-path = "./feedgen.sqlite3"

# The path to a cache directory. Optional.
# cache-dir = "/var/cache/feedgen/"

# The global fetch interval for feeds. Defaults to 2 hours.
# fetch-interval = 7200
# fetch-interval = "1h30m"

# Feedgen adds a random delay before the first update of a feed.
# This option controls the maximum duration of the delay.
# max-initial-fetch-sleep = "45s"

# `feeds` is a map of feeds. The key is used as the feed id in URLs and must be
# unique.
[feeds.hn]
# If `false`, disables updates for this feed. Entries already retrieved
# previously will still be served. Defaults to `true`.
# enabled = true

# The URL to the source page.
request-url = "https://news.ycombinator.com/news"

# A feed-specific update interval. Optional.
fetch-interval = "1h"

# Every feed must have an extractor that parses the source page into feed
# entries.
[feeds.hn.extractor]
# An extractor algorithm to use. Other options in this section are specific to
# the algorithm. Here the XPath extractor is used.
kind = "xpath"

# An XPath expression that returns a nodeset of entries. For each returned node,
# all the other XPath expressions are evaluated relative to it to extract entry
# fields.
entry = "//tr[@class='athing']"

# An XPath expression returning a unique identifier of an entry. Feedgen uses it
# to identify entries: if several entries in the same feed have the same id,
# only one will be stored. Must be non-empty.
id = "@id"

# An XPath expression returning the entry title. Must be non-empty.
title = ".//span[@class='titleline']/a"

# An XPath expression returning the entry description.
description = ".//span[@class='titleline']//text()"

# An XPath expression returning the entry URL. If the returned URL is relative,
# it's joined to the source page URL. Must be a valid relative or absolute URL.
url = ".//span[@class='titleline']/a/@href"

# An XPath expression returning the author of the entry. Optional.
#
# As an aside: note how this expression selects only the first node of the
# nodeset. If the result contains several nodes, they are concatenated.
author = "(following-sibling::tr//a[@class='hnuser'])[1]"

# An XPath expression returning the publication date of the entry. The returned
# value must include timezone information! If the source does not provide it,
# use, e.g., `concat` to insert it into the result. Optional.
pub-date = "concat((following-sibling::tr//span[@class='age']/@title)[1], 'Z')"

# A format description used for parsing the result of `pub-date`.
# See https://time-rs.github.io/book/api/format-description.html for the
# description of the syntax. Note that it must provide timezone information!
# Defaults to the RFC3339 format.
# pub-date-format = "[year]-[month]-[day] [hour]:[minute]:[second] [offset_hour sign:mandatory][offset_minute]"
